export const LOGIN_USER = "LOGIN_USER";

export const FETCH_TIME = "FETCH_TIME";

export const FETCH_TIME_PENDING = 'FETCH_TIME_PENDING';
export const FETCH_TIME_SUCCESS = 'FETCH_TIME_SUCCESS';
export const FETCH_TIME_ERROR = 'FETCH_TIME_ERROR';


